# Generated by Django 4.2.19 on 2025-02-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bitrix24Credentials',
        ),
    ]
