# Generated by Django 4.2.19 on 2025-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0002_delete_bitrix24credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='last_sync',
            field=models.DateTimeField(null=True),
        ),
    ]
