# Generated by Django 4.2.19 on 2025-02-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0003_pipeline_last_sync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-is_main', 'sort'], 'verbose_name': 'Воронка продаж', 'verbose_name_plural': 'Воронки продаж'},
        ),
        migrations.AddField(
            model_name='pipeline',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
