# Generated by Django 4.2.19 on 2025-02-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0004_alter_pipeline_options_pipeline_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='last_sync',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm_connector.pipeline'),
        ),
        migrations.AddField(
            model_name='deal',
            name='probability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='responsible_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm_connector.stage'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['pipeline', 'stage'], name='crm_connect_pipelin_e1ffca_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='crm_connect_created_d1e2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_closed'], name='crm_connect_is_clos_2a6f15_idx'),
        ),
    ]
