# Generated by Django 4.2.19 on 2025-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0005_deal_category_id_deal_details_deal_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('process', 'В процессе'), ('success', 'Успешное завершение'), ('failure', 'Неуспешное завершение')], default='process', max_length=20),
        ),
        migrations.AlterField(
            model_name='stage',
            name='bitrix_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
