# Generated by Django 4.2.19 on 2025-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0006_stage_type_alter_stage_bitrix_id_alter_stage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
