# Generated by Django 4.2.19 on 2025-06-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0007_alter_deal_last_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=255, unique=True, verbose_name='ID заявки в Атласе')),
                ('full_name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Исходные данные из выгрузки')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Синхронизировано с Bitrix24')),
                ('sync_errors', models.TextField(blank=True, null=True, verbose_name='Ошибки синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlas_applications', to='crm_connector.deal', verbose_name='Связанная сделка')),
            ],
            options={
                'verbose_name': 'Заявка из Атласа',
                'verbose_name_plural': 'Заявки из Атласа',
                'indexes': [models.Index(fields=['phone'], name='crm_connect_phone_a4a763_idx'), models.Index(fields=['email'], name='crm_connect_email_2cff75_idx'), models.Index(fields=['full_name', 'region'], name='crm_connect_full_na_9469f4_idx')],
            },
        ),
    ]
