# Generated by Django 4.2.19 on 2025-06-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0009_historicalstage_historicalpipeline_historicaldeal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название статуса')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Статус Атлас',
                'verbose_name_plural': 'Статусы Атлас',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название статуса')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Статус РР',
                'verbose_name_plural': 'Статусы РР',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('description', models.TextField(blank=True, verbose_name='Описание правила')),
                ('atlas_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_connector.atlasstatus', verbose_name='Статус в Атлас')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_rules', to='crm_connector.pipeline', verbose_name='Воронка')),
                ('rr_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_connector.rrstatus', verbose_name='Статус в РР')),
                ('target_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_rules', to='crm_connector.stage', verbose_name='Целевая стадия')),
            ],
            options={
                'verbose_name': 'Правило определения стадии',
                'verbose_name_plural': 'Правила определения стадий',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stagerule',
            constraint=models.CheckConstraint(condition=models.Q(('atlas_status__isnull', False), ('rr_status__isnull', False), _connector='OR'), name='at_least_one_status_required'),
        ),
    ]
