# Generated by Django 4.2.19 on 2025-09-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0011_company_atlasapplication_education_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(max_length=255, unique=True, verbose_name='ID Программы')),
                ('title', models.CharField(max_length=255, verbose_name='Название программы')),
                ('short_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое название программы')),
                ('section', models.JSONField(blank=True, max_length=255, null=True, verbose_name='Разделы')),
                ('topics', models.JSONField(blank=True, max_length=255, null=True, verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Программа Атлас',
                'verbose_name_plural': 'Программы Атлас',
            },
        ),
    ]
