# Generated by Django 4.2.19 on 2025-09-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0012_atlasprogram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atlasprogram',
            options={'verbose_name': 'Программу Атлас', 'verbose_name_plural': 'Программы Атлас'},
        ),
        migrations.AlterField(
            model_name='atlasapplication',
            name='education_progress',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='historicalatlasapplication',
            name='education_progress',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Прогресс'),
        ),
    ]
