# Generated by Django 4.2.19 on 2025-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0013_alter_atlasprogram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasapplication',
            name='JSON_ed_progress',
            field=models.JSONField(blank=True, max_length=1024, null=True, verbose_name='Прогресс JSON'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='JSON_ed_progress',
            field=models.JSONField(blank=True, max_length=1024, null=True, verbose_name='Прогресс JSON'),
        ),
        migrations.AlterField(
            model_name='atlasapplication',
            name='education_progress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='historicalatlasapplication',
            name='education_progress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прогресс'),
        ),
    ]
