# Generated by Django 4.2.19 on 2025-10-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0014_atlasapplication_json_ed_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasapplication',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='atlasapplication',
            name='mail_index',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='mail_index',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
