# Generated by Django 4.2.19 on 2025-10-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0015_atlasapplication_adress_atlasapplication_mail_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atlasapplication',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='atlasapplication',
            old_name='mail_index',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='historicalatlasapplication',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='historicalatlasapplication',
            old_name='mail_index',
            new_name='postal_code',
        ),
    ]
