# Generated by Django 4.2.11 on 2025-10-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_connector', '0016_rename_adress_atlasapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasapplication',
            name='form_apartment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира/другое'),
        ),
        migrations.AddField(
            model_name='atlasapplication',
            name='form_building',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Корпус/другое'),
        ),
        migrations.AddField(
            model_name='atlasapplication',
            name='form_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом/другое'),
        ),
        migrations.AddField(
            model_name='atlasapplication',
            name='form_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс (из формы)'),
        ),
        migrations.AddField(
            model_name='atlasapplication',
            name='form_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион (из формы)'),
        ),
        migrations.AddField(
            model_name='atlasapplication',
            name='form_settlement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='atlasapplication',
            name='form_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица/другое'),
        ),
        migrations.AddField(
            model_name='atlasapplication',
            name='generated_application',
            field=models.FileField(blank=True, null=True, upload_to='applications/generated/', verbose_name='Сгенерированное заявление'),
        ),
        migrations.AddField(
            model_name='atlasapplication',
            name='signed_application',
            field=models.FileField(blank=True, null=True, upload_to='applications/signed/', verbose_name='Подписанное заявление'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='form_apartment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира/другое'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='form_building',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Корпус/другое'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='form_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом/другое'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='form_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс (из формы)'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='form_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион (из формы)'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='form_settlement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='form_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица/другое'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='generated_application',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Сгенерированное заявление'),
        ),
        migrations.AddField(
            model_name='historicalatlasapplication',
            name='signed_application',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Подписанное заявление'),
        ),
    ]
