# Generated by Django 4.2.19 on 2025-04-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сферы')),
                ('description', models.TextField(blank=True, verbose_name='Описание сферы деятельности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сфера деятельности',
                'verbose_name_plural': 'Сферы деятельности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('academic_hours', models.PositiveIntegerField(default=0, verbose_name='Длительность (ак. часы)')),
                ('program_type', models.CharField(choices=[('ADV', 'ДПО ПК'), ('PROFP', 'ПО ПП'), ('PROF', 'ПО')], default='PROF', max_length=5, verbose_name='Вид программы')),
                ('study_form', models.CharField(choices=[('FT', 'Очная'), ('PT', 'Очно-заочная'), ('DIST', 'Заочная')], default='FT', max_length=5, verbose_name='Форма обучения')),
                ('description', models.TextField(blank=True, verbose_name='Описание программы')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (часов)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('activities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_programs', to='education_planner.profactivity', verbose_name='Сфера деятельности')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('description', models.TextField(blank=True, verbose_name='Описание раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='education_planner.educationprogram', verbose_name='Образовательная программа')),
            ],
            options={
                'verbose_name': 'Раздел программы',
                'verbose_name_plural': 'Разделы программы',
                'ordering': ['order', 'name'],
                'unique_together': {('program', 'order')},
            },
        ),
    ]
