# Generated by Django 4.2.19 on 2025-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='final_attestation',
            field=models.CharField(default=0, max_length=255, verbose_name='Итоговая аттестация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programsection',
            name='attestation_form',
            field=models.CharField(blank=True, max_length=255, verbose_name='Форма аттестации'),
        ),
        migrations.AddField(
            model_name='programsection',
            name='workload',
            field=models.PositiveIntegerField(default=0, verbose_name='Трудоёмкость (часы)'),
        ),
    ]
