# Generated by Django 4.2.19 on 2025-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0002_educationprogram_final_attestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='final_lecture_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая аттестация: лекции (Л)'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='final_practice_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая аттестация: практические занятия (ПЗ)'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='final_selfstudy_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая аттестация: самостоятельная работа (СР)'),
        ),
        migrations.AddField(
            model_name='programsection',
            name='lecture_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Лекции (Л)'),
        ),
        migrations.AddField(
            model_name='programsection',
            name='practice_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Практические занятия (ПЗ)'),
        ),
        migrations.AddField(
            model_name='programsection',
            name='selfstudy_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Самостоятельная работа (СР)'),
        ),
    ]
