# Generated by Django 4.2.19 on 2025-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0003_educationprogram_final_lecture_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationprogram',
            name='final_lecture_hours',
        ),
        migrations.RemoveField(
            model_name='educationprogram',
            name='final_practice_hours',
        ),
        migrations.RemoveField(
            model_name='educationprogram',
            name='final_selfstudy_hours',
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='final_attestation',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность итоговой аттестации (ак. часы)'),
        ),
    ]
