# Generated by Django 4.2.19 on 2025-08-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0004_remove_educationprogram_final_lecture_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_operator', models.CharField(choices=[('IRPO', 'ИРПО'), ('VNII', 'ВНИИ')], default='IRPO', max_length=4, verbose_name='Федеральный оператор')),
                ('name', models.CharField(max_length=500, verbose_name='Название договора')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер договора')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('status', models.CharField(choices=[('NEGOTIATION', 'На согласовании'), ('SIGNING', 'На подписании'), ('SIGNED', 'Подписан'), ('COMPLETED', 'Выполнен')], default='NEGOTIATION', max_length=20, verbose_name='Статус')),
                ('document_link', models.URLField(blank=True, verbose_name='Ссылка на договор')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Договор на обучение',
                'verbose_name_plural': 'Договоры на обучение',
                'ordering': ['-signing_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер допсоглашения')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('description', models.TextField(verbose_name='Описание изменений')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('NEGOTIATION', 'На согласовании'), ('SIGNING', 'На подписании'), ('SIGNED', 'Подписан')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('document_link', models.URLField(blank=True, verbose_name='Ссылка на документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='education_planner.eduagreement', verbose_name='Основной договор')),
            ],
            options={
                'verbose_name': 'Дополнительное соглашение',
                'verbose_name_plural': 'Дополнительные соглашения',
                'ordering': ['agreement', '-signing_date', '-created_at'],
                'unique_together': {('agreement', 'number')},
            },
        ),
        migrations.CreateModel(
            name='QuotaChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('ADD', 'Добавление'), ('REMOVE', 'Удаление'), ('MODIFY', 'Изменение')], max_length=10, verbose_name='Тип изменения')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('old_quantity', models.PositiveIntegerField(blank=True, help_text='Для изменений - предыдущее значение', null=True, verbose_name='Старое количество')),
                ('new_quantity', models.PositiveIntegerField(help_text='Для добавления/изменения - новое значение', verbose_name='Новое количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('education_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_changes', to='education_planner.educationprogram', verbose_name='Программа обучения')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_changes', to='education_planner.supplement', verbose_name='Дополнительное соглашение')),
            ],
            options={
                'verbose_name': 'Изменение квоты',
                'verbose_name_plural': 'Изменения квот',
                'ordering': ['supplement', 'education_program', 'region'],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, verbose_name='Регион реализации')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество квоты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='education_planner.eduagreement', verbose_name='Договор')),
                ('education_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='education_planner.educationprogram', verbose_name='Программа обучения')),
            ],
            options={
                'verbose_name': 'Квота',
                'verbose_name_plural': 'Квоты',
                'ordering': ['agreement', 'education_program', 'region'],
                'unique_together': {('agreement', 'education_program', 'region')},
            },
        ),
    ]
