# Generated by Django 4.2.19 on 2025-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0005_eduagreement_supplement_quotachange_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название региона')),
                ('code', models.CharField(blank=True, help_text='Числовой код региона', max_length=10, verbose_name='Код региона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='quota',
            options={'ordering': ['agreement', 'education_program'], 'verbose_name': 'Квота', 'verbose_name_plural': 'Квоты'},
        ),
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='quota',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион (устаревшее)'),
        ),
        migrations.AddField(
            model_name='quota',
            name='regions',
            field=models.ManyToManyField(help_text='Выберите один или несколько регионов', related_name='quotas', to='education_planner.region', verbose_name='Регионы реализации'),
        ),
    ]
