# Generated by Django 4.2.19 on 2025-08-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0006_region_alter_quota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='cost_per_quota',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Стоимость обучения одного человека по данной квоте', max_digits=10, verbose_name='Стоимость за заявку'),
        ),
    ]
