# Generated by Django 4.2.19 on 2025-08-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0007_quota_cost_per_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='end_date',
            field=models.DateField(blank=True, help_text='Планируемая дата окончания обучения по данной квоте', null=True, verbose_name='Дата окончания обучения'),
        ),
        migrations.AddField(
            model_name='quota',
            name='start_date',
            field=models.DateField(blank=True, help_text='Планируемая дата начала обучения по данной квоте', null=True, verbose_name='Дата начала обучения'),
        ),
    ]
