# Generated by Django 4.2.19 on 2025-08-21 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_planner', '0008_quota_end_date_quota_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество потребности')),
                ('document_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на письмо с потребностью')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активная'), ('CANCELLED', 'Отменена'), ('FULFILLED', 'Выполнена'), ('PARTIALLY', 'Частично выполнена')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demands', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='education_planner.quota', verbose_name='Квота')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='education_planner.region', verbose_name='РОИВ (Регион)')),
            ],
            options={
                'verbose_name': 'Потребность РОИВ',
                'verbose_name_plural': 'Потребности РОИВ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Создана'), ('INCREASED', 'Увеличена'), ('DECREASED', 'Уменьшена'), ('CANCELLED', 'Отменена'), ('RESTORED', 'Восстановлена'), ('COMMENT', 'Комментарий')], max_length=20, verbose_name='Действие')),
                ('quantity_before', models.PositiveIntegerField(verbose_name='Количество до')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='Количество после')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата действия')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='education_planner.demand', verbose_name='Потребность')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История изменения потребности',
                'verbose_name_plural': 'История изменений потребностей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotaDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.PositiveIntegerField(verbose_name='Выделенное количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='education_planner.quota', verbose_name='Квота')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_planner.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Распределение квоты',
                'verbose_name_plural': 'Распределения квот',
                'unique_together': {('quota', 'region')},
            },
        ),
    ]
