# Generated by Django 4.2.19 on 2025-08-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0009_demand_demandhistory_quotadistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='region',
            field=models.ForeignKey(help_text='Автоматически заполняется из РОИВ', on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='education_planner.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='ROIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название РОИВ')),
                ('full_name', models.TextField(blank=True, verbose_name='Полное наименование')),
                ('contact_info', models.TextField(blank=True, verbose_name='Контактная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roivs', to='education_planner.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'РОИВ',
                'verbose_name_plural': 'РОИВ',
                'ordering': ['region__name', 'name'],
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.AddField(
            model_name='demand',
            name='roiv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='education_planner.roiv', verbose_name='РОИВ'),
            preserve_default=False,
        ),
    ]
