# Generated by Django 4.2.19 on 2025-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0010_alter_demand_region_roiv_demand_roiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='end_date',
            field=models.DateField(blank=True, help_text='Если указано, потребность относится к конкретному периоду', null=True, verbose_name='Дата окончания периода'),
        ),
        migrations.AddField(
            model_name='demand',
            name='start_date',
            field=models.DateField(blank=True, help_text='Если указано, потребность относится к конкретному периоду', null=True, verbose_name='Дата начала периода'),
        ),
    ]
