# Generated by Django 4.2.19 on 2025-08-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0011_demand_end_date_demand_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала альтернативного периода')),
                ('end_date', models.DateField(verbose_name='Дата окончания альтернативного периода')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество мест в альтернативном периоде')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_quotas', to='education_planner.quota', verbose_name='Основная квота')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_planner.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Альтернативная квота',
                'verbose_name_plural': 'Альтернативные квоты',
                'unique_together': {('quota', 'region', 'start_date', 'end_date')},
            },
        ),
    ]
