# Generated by Django 4.2.19 on 2025-09-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0013_quotadistribution_main_date_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotadistribution',
            name='main_date_quantity',
        ),
        migrations.AlterField(
            model_name='quotadistribution',
            name='allocated_quantity',
            field=models.PositiveIntegerField(verbose_name='Выделенное количество'),
        ),
    ]
