# Generated by Django 5.2.7 on 2026-02-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0014_remove_quotadistribution_main_date_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('department', 'Отдел'), ('human', 'Сотрудник')], verbose_name='Тип контакта')),
                ('department_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название отдела')),
                ('human_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('actual', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='education_planner.roiv', verbose_name='РОИВ')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.CharField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='education_planner.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email‑адреса',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Телефон')),
                ('comment', models.CharField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='education_planner.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
