# Generated by Django 5.2.7 on 2026-02-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0015_contact_email_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionAltNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Псевдоним')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_names', to='education_planner.region', verbose_name='Псевдонимы')),
            ],
            options={
                'verbose_name': 'Псевдоним',
                'verbose_name_plural': 'Псевдонимы',
            },
        ),
    ]
