# Generated by Django 5.2.7 on 2026-02-03 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0016_regionaltnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryROIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('closed', 'Закрыто'), ('integrated', 'Интегрировано')], verbose_name='Статус')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменений')),
                ('priority', models.BooleanField(default=True, verbose_name='Приоритет')),
                ('integrated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrated', to='education_planner.roiv', verbose_name='Интегрировано в')),
                ('roiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='education_planner.roiv', verbose_name='РОИВ')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'История статусов РОИВ',
            },
        ),
        migrations.CreateModel(
            name='NameHistoryROIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('roiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_names', to='education_planner.roiv', verbose_name='Названия')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Названия',
            },
        ),
    ]
