# Generated by Django 5.2.7 on 2026-02-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0017_historyroiv_namehistoryroiv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='roiv',
        ),
        migrations.RemoveField(
            model_name='email',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='historyroiv',
            name='integrated_to',
        ),
        migrations.RemoveField(
            model_name='historyroiv',
            name='roiv',
        ),
        migrations.RemoveField(
            model_name='namehistoryroiv',
            name='roiv',
        ),
        migrations.RemoveField(
            model_name='roiv',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='roiv',
            name='prof_activity',
            field=models.ManyToManyField(blank=True, related_name='ROIV', to='education_planner.profactivity', verbose_name='Сфера деятельности'),
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='HistoryROIV',
        ),
        migrations.DeleteModel(
            name='NameHistoryROIV',
        ),
    ]
