# Generated by Django 5.2.7 on 2026-03-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0018_remove_contact_roiv_remove_email_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Федеральный оператор')),
            ],
            options={
                'verbose_name': 'Федеральный оператор',
                'verbose_name_plural': 'Федеральные операторы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='DOT',
            field=models.BooleanField(default=False, verbose_name='с использованием ДОТ'),
        ),
        migrations.AddField(
            model_name='programsection',
            name='consultation_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Часы консультаций'),
        ),
        migrations.AddField(
            model_name='programsection',
            name='dot_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Часов с применением ДОТ'),
        ),
        migrations.CreateModel(
            name='ProgramRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_form', models.CharField(blank=True, choices=[('FT', 'Очная'), ('PT', 'Очно-заочная'), ('DIST', 'Заочная')], default='FT', max_length=5, null=True, verbose_name='Форма обучения')),
                ('DOT', models.BooleanField(default=False, verbose_name='с ДОТ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='education_planner.federaloperator', verbose_name='Федеральный оператор')),
            ],
            options={
                'verbose_name': 'Требования',
                'verbose_name_plural': 'Требования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_num_type', models.CharField(choices=[('lecture_hours', 'Лекции'), ('practice_hours', 'Практики'), ('selfstudy_hours', 'Самостоятельные'), ('consultation_hours', 'Консультации'), ('dot_hours', 'с ДОТ'), ('workload', 'Общее'), ('contact_hours', 'Контактные часы')], verbose_name='Тип требуемых часов')),
                ('left_num_value', models.PositiveIntegerField(verbose_name='Требуемое количество(%)')),
                ('operator', models.CharField(choices=[('less', '<'), ('more', '>'), ('equal', '=')], verbose_name='Знак')),
                ('right_num_type', models.CharField(choices=[('lecture_hours', 'Лекции'), ('practice_hours', 'Практики'), ('selfstudy_hours', 'Самостоятельные'), ('consultation_hours', 'Консультации'), ('dot_hours', 'с ДОТ'), ('workload', 'Общее'), ('contact_hours', 'Контактные часы')], verbose_name='Требуемое количество от')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='education_planner.programrequirements', verbose_name='Относится к')),
            ],
        ),
    ]
