# Generated by Django 5.2.7 on 2026-03-05 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_planner', '0019_federaloperator_educationprogram_dot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название темы')),
                ('lecture_hours', models.PositiveIntegerField(default=0, verbose_name='Лекции (Л)')),
                ('practice_hours', models.PositiveIntegerField(default=0, verbose_name='Практические занятия (ПЗ)')),
                ('selfstudy_hours', models.PositiveIntegerField(default=0, verbose_name='Самостоятельная работа (СР)')),
                ('consultation_hours', models.PositiveIntegerField(default=0, verbose_name='Консультации (К)')),
                ('dot_hours', models.PositiveIntegerField(default=0, verbose_name='Часов с применением ДОТ')),
                ('workload', models.PositiveIntegerField(default=0, verbose_name='Трудоёмкость (часы)')),
                ('attestation_form', models.CharField(blank=True, max_length=255, verbose_name='Форма аттестации')),
                ('description', models.TextField(blank=True, verbose_name='Описание темы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='education_planner.programsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тема программы',
                'verbose_name_plural': 'Темы программы',
                'ordering': ['order', 'name'],
                'unique_together': {('section', 'order')},
            },
        ),
    ]
