# Generated by Django 5.2.7 on 2026-02-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_planner', '0018_remove_contact_roiv_remove_email_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('department', 'Отдел'), ('person', 'Сотрудник'), ('main', 'Основной'), ('other', 'Другой')], verbose_name='Тип контакта')),
                ('department_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название отдела')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('first_name_dat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя в дательном падеже')),
                ('last_name_dat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия в дательном падеже')),
                ('middle_name_dat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество в дательном падеже')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('position_dat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность в дательном падеже')),
                ('manager', models.BooleanField(default=False, verbose_name='Руководитель организации')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('current', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='FederalDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название округа')),
            ],
            options={
                'verbose_name': 'Федеральный округ',
                'verbose_name_plural': 'Федеральные округа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'тип организации',
                'verbose_name_plural': 'Типы организации',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.CharField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contact_management.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email‑адреса',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Телефон')),
                ('comment', models.CharField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contact_management.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название организации')),
                ('full_name', models.CharField(blank=True, verbose_name='Полное наименование')),
                ('inn', models.CharField(unique=True, verbose_name='ИНН')),
                ('federal_company', models.BooleanField(default=False, verbose_name='Федеральная')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='contact_management.organization')),
                ('prof_activity', models.ManyToManyField(blank=True, related_name='organization', to='education_planner.profactivity', verbose_name='Сфера деятельности')),
                ('roiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='education_planner.roiv', verbose_name='Данные РОИВ')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='contact_management.organizationtype', verbose_name='Тип организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='HistoryOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('closed', 'Закрыто'), ('integrated', 'Интегрировано')], verbose_name='Статус')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменений')),
                ('priority', models.BooleanField(default=True, verbose_name='Приоритет')),
                ('integrated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrated', to='contact_management.organization', verbose_name='Интегрировано в')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='contact_management.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'История изменений организации',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contact_management.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('organizations', models.ManyToManyField(blank=True, related_name='projects', to='contact_management.organization', verbose_name='Организации')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название региона')),
                ('code', models.CharField(blank=True, help_text='Числовой код региона', max_length=10, verbose_name='Код региона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('federalDistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='contact_management.federaldistrict', verbose_name='Округ')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='contact_management.region', verbose_name='Регион'),
        ),
    ]
