# Generated by Django 5.2.7 on 2026-02-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0001_initial'),
        ('education_planner', '0018_remove_contact_roiv_remove_email_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='roiv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='education_planner.roiv', verbose_name='Данные РОИВ'),
        ),
        migrations.AlterField(
            model_name='historyorganization',
            name='integrated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrated', to='contact_management.organization', verbose_name='Интегрировано в'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='contact_management.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='contact_management.organizationtype', verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='region',
            name='federalDistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='contact_management.federaldistrict', verbose_name='Округ'),
        ),
    ]
