# Generated by Django 6.0.2 on 2026-04-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0002_history_and_legacy_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='is_our_side',
            field=models.BooleanField(default=False, verbose_name='Наша организация'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_our_side',
            field=models.BooleanField(default=False, verbose_name='Наша организация'),
        ),
        migrations.CreateModel(
            name='CommunicationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('postal_mail', 'Почта'), ('letter', 'Письмо'), ('messenger', 'Мессенджер'), ('meeting', 'Встреча'), ('call', 'Созвон'), ('phone', 'Телефон')], max_length=20, verbose_name='Канал коммуникации')),
                ('occurred_at', models.DateTimeField(verbose_name='Дата и время коммуникации')),
                ('result', models.TextField(verbose_name='Результат коммуникации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('counterparty_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_interactions', to='contact_management.contact', verbose_name='Контрагент (контакт)')),
                ('counterparty_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_interactions', to='contact_management.organization', verbose_name='Контрагент (организация)')),
                ('our_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='our_communication_interactions', to='contact_management.organization', verbose_name='Наша организация')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_interactions', to='contact_management.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'коммуникация',
                'verbose_name_plural': 'Журнал коммуникаций',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
    ]
